spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: classpath:db/db-changelog.yml
  h2:
    console:
      enabled: true
logging:
  level:
    root: INFO
server:
  port: 8080
springdoc:
  swagger-ui:
    operationsSorter: method

